## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN'])
application_df.head()

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
APPLICATION_VALUE = application_df['APPLICATION_TYPE'].value_counts()
APPLICATION_VALUE

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = APPLICATION_VALUE [APPLICATION_VALUE < 500].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
CLASSIFICATION_COUNTS = application_df['CLASSIFICATION'].value_counts()
CLASSIFICATION_COUNTS

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
CLASSIFICATION_COUNTS[CLASSIFICATION_COUNTS > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = CLASSIFICATION_COUNTS[CLASSIFICATION_COUNTS < 1000].index
# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Look at Name value counts for binning
Name_COUNTS = application_df['NAME'].value_counts()
Name_COUNTS

PARENT BOOSTER USA INC                                                  1260
TOPS CLUB INC                                                            765
UNITED STATES BOWLING CONGRESS INC                                       700
WASHINGTON STATE UNIVERSITY                                              492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                          408
                                                                        ...
ST LOUIS SLAM WOMENS FOOTBALL                                              1
AIESEC ALUMNI IBEROAMERICA CORP                                            1
WEALLBLEEDRED ORG INC                                                      1
AMERICAN SOCIETY FOR STANDARDS IN MEDIUMSHIP & PSYCHICAL INVESTIGATI       1
WATERHOUSE CHARITABLE TR                                                   1
Name: NAME, Length: 19568, dtype: int64

In [10]:
# You may find it helpful to look at Name value counts >1
Name_COUNTS[Name_COUNTS > 1]

PARENT BOOSTER USA INC                                            1260
TOPS CLUB INC                                                      765
UNITED STATES BOWLING CONGRESS INC                                 700
WASHINGTON STATE UNIVERSITY                                        492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                    408
                                                                  ...
VETERANS OF FOREIGH WARS OF THE UNITED STATES DEPT OF COLORADO       2
ETA PHI BETA SORORITY INC                                            2
POINT MAN INTERNATIONAL MINISTRIES                                   2
MULTI COMMUNITY DIVERSIFIED SERVICES INC                             2
VETERANS OF FOREIGN WARS AUXILIARY                                   2
Name: NAME, Length: 792, dtype: int64

In [11]:
# Choose a cutoff value and create a list of name to be replaced
# use the variable name `names_to_replace`
names_to_replace = Name_COUNTS[Name_COUNTS < 50].index

# Replace in dataframe
for cls in names_to_replace:
    application_df['NAME'] = application_df['NAME'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['NAME'].value_counts()

Other                                                                 24545
PARENT BOOSTER USA INC                                                 1260
TOPS CLUB INC                                                           765
UNITED STATES BOWLING CONGRESS INC                                      700
WASHINGTON STATE UNIVERSITY                                             492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC                         408
PTA TEXAS CONGRESS                                                      368
SOROPTIMIST INTERNATIONAL OF THE AMERICAS INC                           331
ALPHA PHI SIGMA                                                         313
TOASTMASTERS INTERNATIONAL                                              293
MOST WORSHIPFUL STRINGER FREE AND ACCEPTED MASONS                       287
LITTLE LEAGUE BASEBALL INC                                              277
INTERNATIONAL ASSOCIATION OF LIONS CLUBS                                266
MOMS CLUB                                                               210
INTERNATIONAL ASSOCIATION OF SHEET METAL AIR RAIL & TRANSPORTATION      206
AMERICAN ASSOCIATION OF UNIVERSITY WOMEN                                197
FARMERS EDUCATIONAL AND COOPERATIVE UNION OF AMERICA                    166
KNIGHTS OF COLUMBUS                                                     158
HABITAT FOR HUMANITY INTERNATIONAL INC                                  154
TENNESSEE ORDER OF THE EASTERN STAR                                     151
VETERANS OF FOREIGN WARS OF THE UNITED STATES AUXILIARY                 144
PTA UTAH CONGRESS                                                       140
THE UNITED STATES PONY CLUBS INC                                        136
CIVITAN INTERNATIONAL                                                   131
SIGMA BETA DELTA INC                                                    127
MONTANA 4-H FOUNDATION INC                                              107
HONOR SOCIETY OF PHI KAPPA PHI                                          107
WASHINGTON STATE GRANGE                                                 106
UNIVERSITY OF WYOMING                                                   105
DEMOLAY INTERNATIONAL                                                   104
SERTOMA INC                                                             103
AIR FORCE ASSOCIATION                                                    99
WORKERS UNITED                                                           97
GAMMA THETA UPSILON                                                      92
INTERNATIONAL ASSOCIATION OF FIRE FIGHTERS                               91
SOCIETY OF SAINT VINCENT DE PAUL COUNCIL OF LOS ANGELES                  87
ROTARY INTERNATIONAL                                                     84
CALIFORNIA GARDEN CLUBS INC                                              76
SWEET ADELINES INTERNATIONAL                                             73
DISABLED AMERICAN VETERANS                                               73
KLEIN SUPPORT GROUPS INC                                                 69
CLEARCREEK I S D SUPPORT GROUPS                                          60
VFW AUXILIARY DEPARTMENT OF OKLAHOMA INC                                 58
CISD EDUCATIONAL SUPPORT GROUPS INC                                      57
DEPARTMENT OF KANSAS LADIES AUXILIARY TO THE VFW OF THE US INC           57
SONS OF CONFEDERATE VETERANS INC                                         56
SLOW FOOD USA INC                                                        55
NATIONAL YOUNG MENS SERVICE LEAGUE                                       54
AMATEUR ATHLETIC UNION OF THE UNITED STATES                              52
LAMBDA THETA ALPHA                                                       52
UNITED FEDERATION OF DOLL CLUBS INC                                      50
UNIVERSITY OF FLORIDA                                                    50
Name: NAME, dtype: int64

In [12]:
application_df

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,Other,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,Other,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,Other,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,Other,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,Other,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,Other,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,Other,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,Other,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,Other,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [13]:
# Convert categorical data to numeric with `pd.get_dummies`
new_application_df= pd.get_dummies(application_df,columns= application_df.dtypes[application_df.dtypes == "object"].index.to_list())
new_application_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AIR FORCE ASSOCIATION,NAME_ALPHA PHI SIGMA,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES,NAME_AMATEUR ATHLETIC UNION OF THE UNITED STATES INC,NAME_AMERICAN ASSOCIATION OF UNIVERSITY WOMEN,NAME_CALIFORNIA GARDEN CLUBS INC,NAME_CISD EDUCATIONAL SUPPORT GROUPS INC,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [14]:
# Split our preprocessed data into our features and target arrays
y = new_application_df["IS_SUCCESSFUL"].values
X = new_application_df.drop(columns= "IS_SUCCESSFUL").values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [15]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [16]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 =  100
hidden_nodes_layer2 = 40

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)
# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               9600

 dense_1 (Dense)             (None, 40)                4040

 dense_2 (Dense)             (None, 1)                 41

=================================================================
Total params: 13681 (53.44 KB)
Trainable params: 13681 (53.44 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [18]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4997 - accuracy: 0.7538
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4817 - accuracy: 0.7619
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4769 - accuracy: 0.7648
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4753 - accuracy: 0.7684
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7686
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4726 - accuracy: 0.7681
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4716 - accuracy: 0.7699
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4702 - accuracy: 0.7697
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4693 - accuracy: 0.7695
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4690 - accuracy: 0.7701
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4682 - accuracy: 0.7697
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4682 - accuracy: 0.7711
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4675 - accuracy: 0.7718
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4667 - accuracy: 0.7728
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4668 - accuracy: 0.7714
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4659 - accuracy: 0.7729
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4657 - accuracy: 0.7732
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4655 - accuracy: 0.7727
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4650 - accuracy: 0.7720
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4648 - accuracy: 0.7730
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4645 - accuracy: 0.7740
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4639 - accuracy: 0.7734
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4630 - accuracy: 0.7753
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4641 - accuracy: 0.7736
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4636 - accuracy: 0.7745
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4628 - accuracy: 0.7740
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4627 - accuracy: 0.7740
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4622 - accuracy: 0.7746
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4624 - accuracy: 0.7746
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4620 - accuracy: 0.7746
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4617 - accuracy: 0.7757
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4614 - accuracy: 0.7747
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4612 - accuracy: 0.7752
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4616 - accuracy: 0.7751
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4609 - accuracy: 0.7759
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4608 - accuracy: 0.7759
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4606 - accuracy: 0.7755
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4608 - accuracy: 0.7751
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4600 - accuracy: 0.7764
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4602 - accuracy: 0.7760
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4598 - accuracy: 0.7753
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4599 - accuracy: 0.7765
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4597 - accuracy: 0.7767
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4589 - accuracy: 0.7764
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4592 - accuracy: 0.7765
Epoch 46/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4591 - accuracy: 0.7757
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4588 - accuracy: 0.7771
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4588 - accuracy: 0.7767
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4590 - accuracy: 0.7761
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4584 - accuracy: 0.7763
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4584 - accuracy: 0.7773
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4584 - accuracy: 0.7759
Epoch 53/100
804/804 [==============================] - 3s 3ms/step - loss: 0.4582 - accuracy: 0.7766
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4580 - accuracy: 0.7766
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4577 - accuracy: 0.7770
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4576 - accuracy: 0.7769
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4576 - accuracy: 0.7766
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4574 - accuracy: 0.7767
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4570 - accuracy: 0.7767
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4573 - accuracy: 0.7772
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4571 - accuracy: 0.7773
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4567 - accuracy: 0.7768
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4572 - accuracy: 0.7767
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4563 - accuracy: 0.7770
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4563 - accuracy: 0.7775
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4564 - accuracy: 0.7774
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4569 - accuracy: 0.7773
Epoch 68/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4565 - accuracy: 0.7775
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4562 - accuracy: 0.7767
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4565 - accuracy: 0.7773
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4564 - accuracy: 0.7778
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4565 - accuracy: 0.7770
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4557 - accuracy: 0.7774
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4559 - accuracy: 0.7775
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4561 - accuracy: 0.7782
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4554 - accuracy: 0.7778
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4560 - accuracy: 0.7783
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4555 - accuracy: 0.7778
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4551 - accuracy: 0.7780
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4559 - accuracy: 0.7771
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4552 - accuracy: 0.7780
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4560 - accuracy: 0.7777
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4558 - accuracy: 0.7778
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4553 - accuracy: 0.7776
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4550 - accuracy: 0.7781
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4549 - accuracy: 0.7779
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4549 - accuracy: 0.7774
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4554 - accuracy: 0.7771
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4549 - accuracy: 0.7786
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4542 - accuracy: 0.7780
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4553 - accuracy: 0.7787
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4552 - accuracy: 0.7787
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4547 - accuracy: 0.7781
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4546 - accuracy: 0.7785
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4550 - accuracy: 0.7781
Epoch 96/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4544 - accuracy: 0.7781
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4547 - accuracy: 0.7785
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4546 - accuracy: 0.7776
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4552 - accuracy: 0.7783
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4539 - accuracy: 0.7781

In [19]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4545 - accuracy: 0.7784
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4546 - accuracy: 0.7784
Epoch 3/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4545 - accuracy: 0.7784
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4542 - accuracy: 0.7779
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4544 - accuracy: 0.7783
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4537 - accuracy: 0.7790
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4547 - accuracy: 0.7782
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4537 - accuracy: 0.7786
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4542 - accuracy: 0.7790
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4543 - accuracy: 0.7783
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4537 - accuracy: 0.7785
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4536 - accuracy: 0.7786
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4539 - accuracy: 0.7791
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4536 - accuracy: 0.7783
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4536 - accuracy: 0.7788
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4538 - accuracy: 0.7790
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4542 - accuracy: 0.7785
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4533 - accuracy: 0.7790
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4537 - accuracy: 0.7784
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4534 - accuracy: 0.7790
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4538 - accuracy: 0.7788
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4544 - accuracy: 0.7786
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4540 - accuracy: 0.7789
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4539 - accuracy: 0.7781
Epoch 25/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4530 - accuracy: 0.7786
Epoch 26/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4533 - accuracy: 0.7790
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4535 - accuracy: 0.7785
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4530 - accuracy: 0.7786
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4532 - accuracy: 0.7785
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4531 - accuracy: 0.7792
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4535 - accuracy: 0.7788
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4534 - accuracy: 0.7790
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4533 - accuracy: 0.7788
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4529 - accuracy: 0.7788
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4530 - accuracy: 0.7789
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4530 - accuracy: 0.7790
Epoch 37/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4547 - accuracy: 0.7783
Epoch 38/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4546 - accuracy: 0.7788
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4545 - accuracy: 0.7790
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4526 - accuracy: 0.7796
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4529 - accuracy: 0.7795
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4529 - accuracy: 0.7787
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4527 - accuracy: 0.7792
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4533 - accuracy: 0.7793
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4528 - accuracy: 0.7789
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4526 - accuracy: 0.7793
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4525 - accuracy: 0.7789
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4526 - accuracy: 0.7785
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4535 - accuracy: 0.7791
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4538 - accuracy: 0.7790
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4525 - accuracy: 0.7790
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4531 - accuracy: 0.7795
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4524 - accuracy: 0.7788
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4528 - accuracy: 0.7792
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4527 - accuracy: 0.7788
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4527 - accuracy: 0.7791
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4525 - accuracy: 0.7791
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4525 - accuracy: 0.7792
Epoch 59/100
804/804 [==============================] - 3s 4ms/step - loss: 0.4525 - accuracy: 0.7791
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4530 - accuracy: 0.7788
Epoch 61/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4526 - accuracy: 0.7788
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4543 - accuracy: 0.7783
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4529 - accuracy: 0.7789
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4520 - accuracy: 0.7797
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4521 - accuracy: 0.7796
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4522 - accuracy: 0.7790
Epoch 67/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4528 - accuracy: 0.7793
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4522 - accuracy: 0.7785
Epoch 69/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4525 - accuracy: 0.7782
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4523 - accuracy: 0.7788
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4529 - accuracy: 0.7786
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4528 - accuracy: 0.7789
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4524 - accuracy: 0.7792
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4538 - accuracy: 0.7789
Epoch 75/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4523 - accuracy: 0.7788
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4518 - accuracy: 0.7791
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4525 - accuracy: 0.7790
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4521 - accuracy: 0.7792
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4523 - accuracy: 0.7786
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4522 - accuracy: 0.7791
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4526 - accuracy: 0.7789
Epoch 82/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4518 - accuracy: 0.7793
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4526 - accuracy: 0.7794
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4521 - accuracy: 0.7789
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4521 - accuracy: 0.7785
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4518 - accuracy: 0.7794
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4540 - accuracy: 0.7788
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4557 - accuracy: 0.7783
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4517 - accuracy: 0.7788
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.4520 - accuracy: 0.7796
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4515 - accuracy: 0.7790
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4521 - accuracy: 0.7792
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4518 - accuracy: 0.7794
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4527 - accuracy: 0.7791
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4521 - accuracy: 0.7791
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4517 - accuracy: 0.7791
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4531 - accuracy: 0.7790
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4517 - accuracy: 0.7792
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4520 - accuracy: 0.7794
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4516 - accuracy: 0.7792

In [20]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5395 - accuracy: 0.7619 - 502ms/epoch - 2ms/step
Loss: 0.5395119190216064, Accuracy: 0.7618659138679504

In [21]:
# Export our model to HDF5 file
nn.save('./AlphabetSoupCharity_Optimization.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(